org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2048m
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.enableBuildAnalyzer=false
android.experimental.runBuildAnalyzer=false
android.attributionCheck.enable=false
android.buildAnalyzer.enabled=false
android.experimental.enableBuildAnalysis=false
android.injected.attribution.check.enabled=false
android.enableBuildAttribution=false
